# Generated by Django 5.0 on 2023-12-12 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passengers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default='Created')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('reservation_date', models.DateField()),
                ('passengerid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='passengers.passenger')),
            ],
        ),
    ]
